import { Suit, Face } from '../constants';

export const fullDeck = [
  { suit: Suit.Diamonds, face: Face.Two },
  { suit: Suit.Diamonds, face: Face.Three },
  { suit: Suit.Diamonds, face: Face.Four },
  { suit: Suit.Diamonds, face: Face.Five },
  { suit: Suit.Diamonds, face: Face.Six },
  { suit: Suit.Diamonds, face: Face.Seven },
  { suit: Suit.Diamonds, face: Face.Eight },
  { suit: Suit.Diamonds, face: Face.Nine },
  { suit: Suit.Diamonds, face: Face.Ten },
  { suit: Suit.Diamonds, face: Face.Jack },
  { suit: Suit.Diamonds, face: Face.Queen },
  { suit: Suit.Diamonds, face: Face.King },
  { suit: Suit.Diamonds, face: Face.Ace },
  { suit: Suit.Clubs, face: Face.Two },
  { suit: Suit.Clubs, face: Face.Three },
  { suit: Suit.Clubs, face: Face.Four },
  { suit: Suit.Clubs, face: Face.Five },
  { suit: Suit.Clubs, face: Face.Six },
  { suit: Suit.Clubs, face: Face.Seven },
  { suit: Suit.Clubs, face: Face.Eight },
  { suit: Suit.Clubs, face: Face.Nine },
  { suit: Suit.Clubs, face: Face.Ten },
  { suit: Suit.Clubs, face: Face.Jack },
  { suit: Suit.Clubs, face: Face.Queen },
  { suit: Suit.Clubs, face: Face.King },
  { suit: Suit.Clubs, face: Face.Ace },
  { suit: Suit.Hearts, face: Face.Two },
  { suit: Suit.Hearts, face: Face.Three },
  { suit: Suit.Hearts, face: Face.Four },
  { suit: Suit.Hearts, face: Face.Five },
  { suit: Suit.Hearts, face: Face.Six },
  { suit: Suit.Hearts, face: Face.Seven },
  { suit: Suit.Hearts, face: Face.Eight },
  { suit: Suit.Hearts, face: Face.Nine },
  { suit: Suit.Hearts, face: Face.Ten },
  { suit: Suit.Hearts, face: Face.Jack },
  { suit: Suit.Hearts, face: Face.Queen },
  { suit: Suit.Hearts, face: Face.King },
  { suit: Suit.Hearts, face: Face.Ace },
  { suit: Suit.Spades, face: Face.Two },
  { suit: Suit.Spades, face: Face.Three },
  { suit: Suit.Spades, face: Face.Four },
  { suit: Suit.Spades, face: Face.Five },
  { suit: Suit.Spades, face: Face.Six },
  { suit: Suit.Spades, face: Face.Seven },
  { suit: Suit.Spades, face: Face.Eight },
  { suit: Suit.Spades, face: Face.Nine },
  { suit: Suit.Spades, face: Face.Ten },
  { suit: Suit.Spades, face: Face.Jack },
  { suit: Suit.Spades, face: Face.Queen },
  { suit: Suit.Spades, face: Face.King },
  { suit: Suit.Spades, face: Face.Ace },
] as const;

export const fullDeckWithJokers = [
  ...fullDeck,
  { suit: Suit.Joker, face: Face.Joker },
  { suit: Suit.Joker, face: Face.Joker },
  { suit: Suit.Joker, face: Face.Joker },
  { suit: Suit.Joker, face: Face.Joker },
] as const;
