import { Suit, Face } from '../../card/constants';

export const fullDeckValue = [
  [Face.Ace, Suit.Diamonds],
  [Face.Two, Suit.Diamonds],
  [Face.Three, Suit.Diamonds],
  [Face.Four, Suit.Diamonds],
  [Face.Five, Suit.Diamonds],
  [Face.Six, Suit.Diamonds],
  [Face.Seven, Suit.Diamonds],
  [Face.Eight, Suit.Diamonds],
  [Face.Nine, Suit.Diamonds],
  [Face.Ten, Suit.Diamonds],
  [Face.Jack, Suit.Diamonds],
  [Face.Queen, Suit.Diamonds],
  [Face.King, Suit.Diamonds],

  [Face.Ace, Suit.Clubs],
  [Face.Two, Suit.Clubs],
  [Face.Three, Suit.Clubs],
  [Face.Four, Suit.Clubs],
  [Face.Five, Suit.Clubs],
  [Face.Six, Suit.Clubs],
  [Face.Seven, Suit.Clubs],
  [Face.Eight, Suit.Clubs],
  [Face.Nine, Suit.Clubs],
  [Face.Ten, Suit.Clubs],
  [Face.Jack, Suit.Clubs],
  [Face.Queen, Suit.Clubs],
  [Face.King, Suit.Clubs],

  [Face.Ace, Suit.Hearts],
  [Face.Two, Suit.Hearts],
  [Face.Three, Suit.Hearts],
  [Face.Four, Suit.Hearts],
  [Face.Five, Suit.Hearts],
  [Face.Six, Suit.Hearts],
  [Face.Seven, Suit.Hearts],
  [Face.Eight, Suit.Hearts],
  [Face.Nine, Suit.Hearts],
  [Face.Ten, Suit.Hearts],
  [Face.Jack, Suit.Hearts],
  [Face.Queen, Suit.Hearts],
  [Face.King, Suit.Hearts],

  [Face.Ace, Suit.Spades],
  [Face.Two, Suit.Spades],
  [Face.Three, Suit.Spades],
  [Face.Four, Suit.Spades],
  [Face.Five, Suit.Spades],
  [Face.Six, Suit.Spades],
  [Face.Seven, Suit.Spades],
  [Face.Eight, Suit.Spades],
  [Face.Nine, Suit.Spades],
  [Face.Ten, Suit.Spades],
  [Face.Jack, Suit.Spades],
  [Face.Queen, Suit.Spades],
  [Face.King, Suit.Spades],
] as const;

export const fullDeckNdo = [
  [Face.Ace, Suit.Hearts],
  [Face.Two, Suit.Hearts],
  [Face.Three, Suit.Hearts],
  [Face.Four, Suit.Hearts],
  [Face.Five, Suit.Hearts],
  [Face.Six, Suit.Hearts],
  [Face.Seven, Suit.Hearts],
  [Face.Eight, Suit.Hearts],
  [Face.Nine, Suit.Hearts],
  [Face.Ten, Suit.Hearts],
  [Face.Jack, Suit.Hearts],
  [Face.Queen, Suit.Hearts],
  [Face.King, Suit.Hearts],

  [Face.Ace, Suit.Clubs],
  [Face.Two, Suit.Clubs],
  [Face.Three, Suit.Clubs],
  [Face.Four, Suit.Clubs],
  [Face.Five, Suit.Clubs],
  [Face.Six, Suit.Clubs],
  [Face.Seven, Suit.Clubs],
  [Face.Eight, Suit.Clubs],
  [Face.Nine, Suit.Clubs],
  [Face.Ten, Suit.Clubs],
  [Face.Jack, Suit.Clubs],
  [Face.Queen, Suit.Clubs],
  [Face.King, Suit.Clubs],

  [Face.King, Suit.Diamonds],
  [Face.Queen, Suit.Diamonds],
  [Face.Jack, Suit.Diamonds],
  [Face.Ten, Suit.Diamonds],
  [Face.Nine, Suit.Diamonds],
  [Face.Eight, Suit.Diamonds],
  [Face.Seven, Suit.Diamonds],
  [Face.Six, Suit.Diamonds],
  [Face.Five, Suit.Diamonds],
  [Face.Four, Suit.Diamonds],
  [Face.Three, Suit.Diamonds],
  [Face.Two, Suit.Diamonds],
  [Face.Ace, Suit.Diamonds],

  [Face.King, Suit.Spades],
  [Face.Queen, Suit.Spades],
  [Face.Jack, Suit.Spades],
  [Face.Ten, Suit.Spades],
  [Face.Nine, Suit.Spades],
  [Face.Eight, Suit.Spades],
  [Face.Seven, Suit.Spades],
  [Face.Six, Suit.Spades],
  [Face.Five, Suit.Spades],
  [Face.Four, Suit.Spades],
  [Face.Three, Suit.Spades],
  [Face.Two, Suit.Spades],
  [Face.Ace, Suit.Spades],
] as const;
